

  
    
  


  





  

<!DOCTYPE html>
<html lang="en-us">
  <head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Hugo 0.31 with theme Tranquilpeak 0.4.3-BETA">
    <title>Scraping Presidential Approval</title>
    <meta name="author" content="Daniel Mikel">
    <meta name="keywords" content="">

    <link rel="icon" href="/favicon.png">
    

    
    <meta name="description" content="This is my first data scrapping project. I’ve taken a few tutorials in the past, but never really took the time to try out the technique. Data scrapping seems like a pretty handy tool to have in a world where people really don’t give a shit if you can use their data (and sometimes discourage it).
I’ve been pretty much addicted to 538 politics since at least 2012, but probably before that.">
    <meta property="og:description" content="This is my first data scrapping project. I’ve taken a few tutorials in the past, but never really took the time to try out the technique. Data scrapping seems like a pretty handy tool to have in a world where people really don’t give a shit if you can use their data (and sometimes discourage it).
I’ve been pretty much addicted to 538 politics since at least 2012, but probably before that.">
    <meta property="og:type" content="blog">
    <meta property="og:title" content="Scraping Presidential Approval">
    <meta property="og:url" content="/2017/12/scraping-presidential-approval/">
    <meta property="og:site_name" content="Abies">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Abies">
    <meta name="twitter:description" content="This is my first data scrapping project. I’ve taken a few tutorials in the past, but never really took the time to try out the technique. Data scrapping seems like a pretty handy tool to have in a world where people really don’t give a shit if you can use their data (and sometimes discourage it).
I’ve been pretty much addicted to 538 politics since at least 2012, but probably before that.">
    
      <meta name="twitter:creator" content="@dmikel2010">
    
    

    
    

    
      <meta property="og:image" content="https://pbs.twimg.com/profile_images/924482790019686400/b990M9b3_400x400.jpg">
    

    
    
    

    

    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.min.css" integrity="sha256-vuXZ9LGmmwtjqFX1F+EKin1ThZMub58gKULUyf0qECk=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/helpers/jquery.fancybox-thumbs.min.css" integrity="sha256-SEa4XYAHihTcEP1f5gARTB2K26Uk8PsndQYHQC1f4jU=" crossorigin="anonymous" />
    
    
    <link rel="stylesheet" href="/css/style-jsjn0006wyhpyzivf6yceb31gvpjatbcs3qzjvlumobfnugccvobqwxnnaj8.min.css" />
    
    

    
      
    
    
  </head>

  <body>
    <div id="blog">
      <header id="header" data-behavior="2">
  <i id="btn-open-sidebar" class="fa fa-lg fa-bars"></i>
  <div class="header-title">
    <a class="header-title-link" href="/">Abies</a>
  </div>
  
    
      <a class="header-right-picture "
         href="/#about">
    
    
    
      
        <img class="header-picture" src="https://pbs.twimg.com/profile_images/924482790019686400/b990M9b3_400x400.jpg" alt="Author&#39;s picture" />
      
    
    </a>
  
</header>

      <nav id="sidebar" data-behavior="2">
  <div class="sidebar-container">
    
      <div class="sidebar-profile">
        <a href="/#about">
          <img class="sidebar-profile-picture" src="https://pbs.twimg.com/profile_images/924482790019686400/b990M9b3_400x400.jpg" alt="Author&#39;s picture" />
        </a>
        <h4 class="sidebar-profile-name">Daniel Mikel</h4>
        
          <h5 class="sidebar-profile-bio">This is a blog I started for myself to practice and share my R progress. This website is powered by blogdown and run through Rstudio</h5>
        
      </div>
    
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/">
    
      <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      
      <span class="sidebar-button-desc">Home</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/categories">
    
      <i class="sidebar-button-icon fa fa-lg fa-bookmark"></i>
      
      <span class="sidebar-button-desc">Categories</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/tags">
    
      <i class="sidebar-button-icon fa fa-lg fa-tags"></i>
      
      <span class="sidebar-button-desc">Tags</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/archives">
    
      <i class="sidebar-button-icon fa fa-lg fa-archive"></i>
      
      <span class="sidebar-button-desc">Archives</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="/#about">
    
      <i class="sidebar-button-icon fa fa-lg fa-question"></i>
      
      <span class="sidebar-button-desc">About</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      
  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://github.com/daniel-mikel">
    
      <i class="sidebar-button-icon fa fa-lg fa-github"></i>
      
      <span class="sidebar-button-desc">GitHub</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://twitter.com/dmikel2010">
    
      <i class="sidebar-button-icon fa fa-lg fa-twitter"></i>
      
      <span class="sidebar-button-desc">Twitter</span>
    </a>
  </li>

  <li class="sidebar-button">
    
      <a class="sidebar-button-link " href="https://www.linkedin.com/in/daniel-mikel-32428350/">
    
      <i class="sidebar-button-icon fa fa-lg fa-linkedin"></i>
      
      <span class="sidebar-button-desc">Linkedin</span>
    </a>
  </li>


    </ul>
    <ul class="sidebar-buttons">
      

    </ul>
  </div>
</nav>

      

      <div id="main" data-behavior="2"
        class="
               hasCoverMetaIn
               ">
        <article class="post" itemscope itemType="http://schema.org/BlogPosting">
          
          
            <div class="post-header main-content-wrap text-left">
  
    <h1 class="post-title" itemprop="headline">
      Scraping Presidential Approval
    </h1>
  
  
  <div class="postShorten-meta post-meta">
    
      <time itemprop="datePublished" datetime="2017-12-14T21:19:12-05:00">
        
  December 14, 2017

      </time>
    
    
  </div>

</div>
          
          <div class="post-content markdown" itemprop="articleBody">
            <div class="main-content-wrap">
              <p>This is my first data scrapping project. I’ve taken a few tutorials in the past, but never really took the time to try out the technique. Data scrapping seems like a pretty handy tool to have in a world where people really don’t give a shit if you can use their data (and sometimes discourage it).</p>
<p>I’ve been pretty much addicted to 538 politics since at least 2012, but probably before that. And by probably addicted I mean that I am. So it makes sense that I would try to funnel my addiction into more productive outlets.</p>
<p>Originally I was looking for US congressional election data, which I’ve still got my eye out for (a convenient place to take historical data, individual election results are pretty easy to find). I stumbled onto this database/web app from the University of California at Santa Barbara’s <a href="http://www.presidency.ucsb.edu/index.php">The American Presidency Project</a>. It’s a pretty sweet place that I’ll probably frequent for future projects. They also host US Presidential approval rates since July 1941. We’ll start with scrapping Obama’s presidential approval ratings.</p>
<p>We’ll need a few packages for this project:</p>
<pre class="r"><code>library(&quot;rvest&quot;)
library(&quot;tidyverse&quot;)
library(&quot;zoo&quot;)</code></pre>
<ul>
<li><p><strong>rvest</strong> will be used to scrape the data from the website</p></li>
<li><p><strong>tidyverse</strong> will be used for manipulating the data and graphing it (tidyverse includes several packages, of which dplyr, tidyr, and ggplot2, which are the packages from the tidyverse we’ll actually be using</p></li>
<li><p><strong>zoo</strong> which is handy for manipulating dates, we’ll use this to create rolling averages of our data for graphing</p></li>
</ul>
<p>We’ll also use the google chrome plugin SelectorGaget, for identifying html code when scraping. I have a screenshot below of what it looks like after selecting the appropriate area. In SelectorGaget green represents the area you’ve clicked to tell it you want that object, yellow represent what it thinks you want, and red represents areas you’ve clicked to unselect from the objects you want. It’s easier than it sounds.</p>
<div class="figure">
<img src="/images/ucsb_pres_1.png" alt="SelectorGaget Example" />
<p class="caption">SelectorGaget Example</p>
</div>
<p>Now we’ll copy paste the website into R, save it as the string my_url like we would a file directory and use rvest’s read_html() function to read the website into R in a way that R understands. We’ll scrape the data we want with rvest::html_nodes(), supplying it with the object we created from read_html() and the css path we got from SelectorGaget. Then we convert these html nodes to a character vector with html_text(), the argument tell’s R to delete white space character strings in our vector.</p>
<pre class="r"><code>my_url &lt;- &#39;http://www.presidency.ucsb.edu/data/popularity.php?pres=44&amp;sort=time&amp;direct=DESC&amp;Submit=DISPLAY&#39;

my_webpage &lt;- read_html(my_url)

approval_html &lt;- html_nodes(my_webpage, &#39;.listdate&#39;)
approval_data &lt;- html_text(approval_html, trim = TRUE)</code></pre>
<p>Let’s see what we have:</p>
<pre class="r"><code>length(approval_data)</code></pre>
<pre><code>## [1] 19510</code></pre>
<pre class="r"><code>head(approval_data, n = 31)</code></pre>
<pre><code>##  [1] &quot;&quot;             &quot;Barack Obama&quot; &quot;01/17/2017&quot;   &quot;01/19/2017&quot;  
##  [5] &quot;&quot;             &quot;59&quot;           &quot;37&quot;           &quot;4&quot;           
##  [9] &quot;&quot;             &quot;01/15/2017&quot;   &quot;01/18/2017&quot;   &quot;&quot;            
## [13] &quot;58&quot;           &quot;38&quot;           &quot;4&quot;            &quot;&quot;            
## [17] &quot;01/14/2017&quot;   &quot;01/17/2017&quot;   &quot;&quot;             &quot;57&quot;          
## [21] &quot;39&quot;           &quot;4&quot;            &quot;&quot;             &quot;01/13/2017&quot;  
## [25] &quot;01/15/2017&quot;   &quot;&quot;             &quot;57&quot;           &quot;38&quot;          
## [29] &quot;5&quot;            &quot;&quot;             &quot;01/12/2017&quot;</code></pre>
<p>So the data is a little messy out of the box. We’ve got 19,510 points of data, and some of them are even useful! It’s an easy fix. We just need to clean up the empty character strings, and delete the first string with positive data in it, since it doesn’t fit the larger pattern.</p>
<pre class="r"><code>approval_data[approval_data==&quot;&quot;] &lt;- NA
approval_data[1:2] &lt;- NA
approval_data &lt;- na.omit(approval_data)
head(approval_data, n = 25)</code></pre>
<pre><code>##  [1] &quot;01/17/2017&quot; &quot;01/19/2017&quot; &quot;59&quot;         &quot;37&quot;         &quot;4&quot;         
##  [6] &quot;01/15/2017&quot; &quot;01/18/2017&quot; &quot;58&quot;         &quot;38&quot;         &quot;4&quot;         
## [11] &quot;01/14/2017&quot; &quot;01/17/2017&quot; &quot;57&quot;         &quot;39&quot;         &quot;4&quot;         
## [16] &quot;01/13/2017&quot; &quot;01/15/2017&quot; &quot;57&quot;         &quot;38&quot;         &quot;5&quot;         
## [21] &quot;01/12/2017&quot; &quot;01/14/2017&quot; &quot;57&quot;         &quot;39&quot;         &quot;4&quot;</code></pre>
<p>It looks like we’ve got a clear pattern now. The dates correspond to the date range of the polling, then we have the approval rating, disapproval rating, and undecided rating. That makes 5 columns of data for the entirety of the set. We can convert this into a data frame now.</p>
<pre class="r"><code>obama_matrix &lt;- matrix(approval_data, ncol = 5, byrow = TRUE)
obama_df &lt;- as.data.frame(obama_matrix, stringsAsFactors = FALSE)
names(obama_df) &lt;- c(&quot;start_date&quot;, &quot;end_date&quot;, &quot;approve&quot;, &quot;disapprove&quot;, &quot;unsure&quot;)</code></pre>
<p>Now we need to get everything out of a character vector.</p>
<pre class="r"><code>obama_df[] &lt;- lapply(obama_df, type.convert)

obama_df$start_date &lt;- as.Date(obama_df$start_date, 
                               format = &quot;%m/%d/%Y&quot;)
obama_df$end_date &lt;- as.Date(obama_df$end_date, 
                             format = &quot;%m/%d/%Y&quot;)

str(obama_df)</code></pre>
<pre><code>## &#39;data.frame&#39;:    2787 obs. of  5 variables:
##  $ start_date: Date, format: &quot;2017-01-17&quot; &quot;2017-01-15&quot; ...
##  $ end_date  : Date, format: &quot;2017-01-19&quot; &quot;2017-01-18&quot; ...
##  $ approve   : int  59 58 57 57 57 58 57 57 55 56 ...
##  $ disapprove: int  37 38 39 38 39 37 40 40 42 40 ...
##  $ unsure    : int  4 4 4 5 4 5 3 3 3 0 ...</code></pre>
<p>And we can see what we have with a quick plot.</p>
<pre class="r"><code>ggplot(obama_df, aes(x = end_date, y = approve)) +
  geom_point() </code></pre>
<p><img src="/post/2017-12-14-scraping-presidential-approval-ratings_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Now lets manipulate the data a little bit, so it’s easier to plot.</p>
<pre class="r"><code>tidy_obama &lt;- obama_df %&gt;%
  gather(opinion, percent, -c(start_date, end_date))

ggplot(tidy_obama, aes(x = end_date, y = percent, group = opinion, col = opinion)) +
  geom_jitter()</code></pre>
<p><img src="/post/2017-12-14-scraping-presidential-approval-ratings_files/figure-html/unnamed-chunk-9-1.png" width="768" /></p>
<p>We’ve got a lot of data points on that plot. about 2787 per each type of rating actually. If we want a more easily interpretable plot we should adjust the opacity of the scatter plot, then we can add a moving average to more easily track the data actually being presented.</p>
<pre class="r"><code>ggplot(tidy_obama, aes(x = end_date, y = percent, group = opinion, col = opinion)) +
  geom_jitter(alpha = 0.5, shape = 1) +
  geom_line(aes(y=rollmean(percent, 15, na.pad=TRUE)), size = 1.3, alpha = 0.8) +
  theme_minimal() </code></pre>
<p><img src="/post/2017-12-14-scraping-presidential-approval-ratings_files/figure-html/unnamed-chunk-10-1.png" width="768" /></p>
<p>At first I tried a loess function to smooth the groupings but didn’t get a result I wanted. Then I googled my way to stackoverflow, which is how I solve most of my R related issues, and found the rollmean() function from the zoo package. It gave me the result I was looking for.</p>
<p>As a further note, when you select a new president in the UCSB web app, the URL changes the middle two digit number to the number of the presidency. I think it would be easy to build a web crawler from this, since it would be pretty easy to create a function that will scrape all of the presidential approval ratings. But honestly it’s 9 pm and I’m well on my way to putting in 60 hours at work this week, so that will have to wait until another day.</p>

              
            </div>
          </div>
          <div id="post-footer" class="post-footer main-content-wrap">
            
              
            
            
  <div class="post-actions-wrap">
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--disabled">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2017/11/california-wine----part-1/" data-tooltip="California Wine  - Part 1">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=/2017/12/scraping-presidential-approval/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=/2017/12/scraping-presidential-approval/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://plus.google.com/share?url=/2017/12/scraping-presidential-approval/">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  </div>


            
              
                <div id="disqus_thread">
  <noscript>Please enable JavaScript to view the <a href="//disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>
              
            
          </div>
        </article>
        <footer id="footer" class="main-content-wrap">
  <span class="copyrights">
    &copy; 2017 Daniel Mikel. All Rights Reserved
  </span>
</footer>

      </div>
      <div id="bottom-bar" class="post-bottom-bar" data-behavior="2">
        
  <div class="post-actions-wrap">
      <nav >
        <ul class="post-actions post-action-nav">
          
            <li class="post-action">
              
                <a class="post-action-btn btn btn--disabled">
              
                  <i class="fa fa-angle-left"></i>
                  <span class="hide-xs hide-sm text-small icon-ml">NEXT</span>
                </a>
            </li>
            <li class="post-action">
              
                <a class="post-action-btn btn btn--default tooltip--top" href="/2017/11/california-wine----part-1/" data-tooltip="California Wine  - Part 1">
              
                  <span class="hide-xs hide-sm text-small icon-mr">PREVIOUS</span>
                  <i class="fa fa-angle-right"></i>
                </a>
            </li>
          
        </ul>
      </nav>
    <ul class="post-actions post-action-share" >
      
        <li class="post-action hide-lg hide-md hide-sm">
          <a class="post-action-btn btn btn--default btn-open-shareoptions" href="#btn-open-shareoptions">
            <i class="fa fa-share-alt"></i>
          </a>
        </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://www.facebook.com/sharer/sharer.php?u=/2017/12/scraping-presidential-approval/">
              <i class="fa fa-facebook-official"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://twitter.com/intent/tweet?text=/2017/12/scraping-presidential-approval/">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
        
          <li class="post-action hide-xs">
            <a class="post-action-btn btn btn--default" target="new" href="https://plus.google.com/share?url=/2017/12/scraping-presidential-approval/">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        
      
      
        <li class="post-action">
          <a class="post-action-btn btn btn--default" href="#disqus_thread">
            <i class="fa fa-comment-o"></i>
          </a>
        </li>
      
      <li class="post-action">
        
          <a class="post-action-btn btn btn--default" href="#">
        
          <i class="fa fa-list"></i>
        </a>
      </li>
    </ul>
  </div>


      </div>
      <div id="share-options-bar" class="share-options-bar" data-behavior="2">
  <i id="btn-close-shareoptions" class="fa fa-close"></i>
  <ul class="share-options">
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://www.facebook.com/sharer/sharer.php?u=%2F2017%2F12%2Fscraping-presidential-approval%2F">
          <i class="fa fa-facebook-official"></i><span>Share on Facebook</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://twitter.com/intent/tweet?text=%2F2017%2F12%2Fscraping-presidential-approval%2F">
          <i class="fa fa-twitter"></i><span>Share on Twitter</span>
        </a>
      </li>
    
      <li class="share-option">
        <a class="share-option-btn" target="new" href="https://plus.google.com/share?url=%2F2017%2F12%2Fscraping-presidential-approval%2F">
          <i class="fa fa-google-plus"></i><span>Share on Google&#43;</span>
        </a>
      </li>
    
  </ul>
</div>
<div id="share-options-mask" class="share-options-mask"></div>
    </div>
    
    <div id="about">
  <div id="about-card">
    <div id="about-btn-close">
      <i class="fa fa-remove"></i>
    </div>
    
      <img id="about-card-picture" src="https://pbs.twimg.com/profile_images/924482790019686400/b990M9b3_400x400.jpg" alt="Author&#39;s picture" />
    
    <h4 id="about-card-name">Daniel Mikel</h4>
    
      <div id="about-card-bio">This is a blog I started for myself to practice and share my R progress. This website is powered by blogdown and run through Rstudio</div>
    
    
    
      <div id="about-card-location">
        <i class="fa fa-map-marker"></i>
        <br/>
        Sacramento, CA
      </div>
    
  </div>
</div>

    <div id="algolia-search-modal" class="modal-container">
  <div class="modal">
    <div class="modal-header">
      <span class="close-button"><i class="fa fa-close"></i></span>
      <a href="https://algolia.com" target="_blank" rel="noopener" class="searchby-algolia text-color-light link-unstyled">
        <span class="searchby-algolia-text text-color-light text-small">by</span>
        <img class="searchby-algolia-logo" src="https://www.algolia.com/static_assets/images/press/downloads/algolia-light.svg">
      </a>
      <i class="search-icon fa fa-search"></i>
      <form id="algolia-search-form">
        <input type="text" id="algolia-search-input" name="search"
          class="form-control input--large search-input" placeholder="Search" />
      </form>
    </div>
    <div class="modal-body">
      <div class="no-result text-color-light text-center">no post found</div>
      <div class="results">
        
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/12/scraping-presidential-approval/">
                <h3 class="media-heading">Scraping Presidential Approval</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Dec 12, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">This is my first data scrapping project. I’ve taken a few tutorials in the past, but never really took the time to try out the technique. Data scrapping seems like a pretty handy tool to have in a world where people really don’t give a shit if you can use their data (and sometimes discourage it).
I’ve been pretty much addicted to 538 politics since at least 2012, but probably before that.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/11/california-wine----part-1/">
                <h3 class="media-heading">California Wine  - Part 1</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Nov 11, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">The United States Department of Agriculture publishes contract level price and volume data for California grapes crushed and used for wine. This allows us to see each purchase of a wine variety, what variety, it’s price, and the tonnage in the purchased amoung, giving us a disaggregated level data of data ripe for analysis. This is intended to be the first in a series of blog posts analysing the dynamics of the California.</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
          <div class="media">
            
            <div class="media-body">
              <a class="link-unstyled" href="/2017/11/cleaning-data/">
                <h3 class="media-heading">Cleaning Data</h3>
              </a>
              <span class="media-meta">
                <span class="media-date text-small">
                  Nov 11, 2017
                </span>
              </span>
              <div class="media-content hide-xs font-merryweather">California Wine The first project I’m going to work on is with California Wine Grape Data. The data we’ll start with is hosted by the United States Department of Agriculture’s Grape Crush Report which collects wine price, production, and acreage for California by wine variety disaggregated to either the Grape Price District (this can mean one county or several counties) or the individual grape purchasing contract.
California Grape Price Districts Image</div>
            </div>
            <div style="clear:both;"></div>
            <hr>
          </div>
        
      </div>
    </div>
    <div class="modal-footer">
      <p class="results-count text-medium"
         data-message-zero="no post found"
         data-message-one="1 post found"
         data-message-other="{n} posts found">
         3 posts found
      </p>
    </div>
  </div>
</div>
    
  
    
    <div id="cover" style="background-image:url('/images/john_muir_yosemite.png');"></div>
  


    
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.7/js/jquery.fancybox.min.js" integrity="sha256-GEAnjcTqVP+vBp3SSc8bEDQqvWAZMiHyUSIorrWwH50=" crossorigin="anonymous"></script>


<script src="/js/script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js"></script>



<script>
$(document).ready(function() {
  hljs.configure({ classPrefix: '', useBR: false });
  $('pre.code-highlight > code, pre > code').each(function(i, block) {
    if (!$(this).hasClass('codeblock')) {
      $(this).addClass('codeblock');
    }
    hljs.highlightBlock(block);
  });
});
</script>


  
    
      <script>
        var disqus_config = function () {
          this.page.url = '\/2017\/12\/scraping-presidential-approval\/';
          
            this.page.identifier = '\/2017\/12\/scraping-presidential-approval\/'
          
        };
        (function() {
          
          
          if (window.location.hostname == "localhost") {
            return;
          }
          var d = document, s = d.createElement('script');
          var disqus_shortname = 'Daniel Mikel';
          s.src = '//' + disqus_shortname + '.disqus.com/embed.js';

          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
        })();
      </script>
    
  



    
  </body>
</html>

